New function and some interface changes
shree675/slash-cookies pull request #1
Opened 2023-12-11 02:56 UTC by guilhermebarbosa03

Added a button that allows you to remove the rules from all websites. Also added a title for the buttons when you hover the mouse.

2023-12-11 17:31 UTC, shree675 commented
@guilhermebarbosa03 Thank you for your contribution. I will review the changes and merge it as soon as I get time

2023-12-11 18:04 UTC, shree675 requested changes

2023-12-11 18:04 UTC, shree675 commented on popup.js
>        chrome.storage.local.set({ mappings: mappings });
Can we replace these four lines by the following:
```suggestion
      chrome.storage.local.set({ mappings: {} });
```
This will avoid the loop. Let me know if this method will cause any issue.

2023-12-11 21:47 UTC, guilhermebarbosa03 commented on popup.js
>        chrome.storage.local.set({ mappings: mappings });
Good idea. This will be more efficient.

2023-12-13 17:02 UTC, shree675 approved these changes

2023-12-13 17:04 UTC, merged